--------------------------------------------------------
--  파일이 생성됨 - 목요일-2월-27-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MT_USER
--------------------------------------------------------

  CREATE TABLE "HR"."MT_USER" 
   (	"SEQ" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"DEPARTMENT_NAME" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"DEPARTMENT_CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MT_USER
SET DEFINE OFF;
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (1,'hyunji','123','오현지','스마트미디어인재개발원','마케팅','팀장','010','ohj@','SM0123','SMMA01');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (23,'ohyunji','123456','오현지','스마트미디어인재개발원','개발팀','팀장','01012345678','ohj@naver.com','SM0123','SMDM02');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (25,'hyunbin','123456','현빈','전남대학교','회계팀','사원','01030338102','hyunbin@gamil','JU0123','JUHG01');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (26,'cty02','123456789','최태영','스마트미디어인재개발원','개발팀','인턴','01012345678','cty02@gmail.com','SM0123','SMDM02');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (27,'cty01','123456','최태영','스마트미디어인재개발원','개발팀','인턴','01012345678','cty01@gmail.com','SM0123','SMDM02');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (24,'suji','123456','수지','스마트미디어인재개발원','개발팀','사원','01056781234','suji@gamil','SM0123','SMDM02');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (21,'park','456','박서준','스마트미디어인재개발원','개발팀','사원','01030338102','ohj@gamil','SM0123','SMDM02');
Insert into HR.MT_USER (SEQ,ID,PW,NAME,COMPANY_NAME,DEPARTMENT_NAME,POSITION,PHONE,EMAIL,COMPANY_CODE,DEPARTMENT_CODE) values (22,'kim','789','김다미','스마트미디어인재개발원','개발팀','사원','01012345678','kdm@gamil','SM0123','SMDM02');
